CREATE DATABASE [AplikacjeWielkoskalowe]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AplikacjeWielkoskalowe', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\AplikacjeWielkoskalowe.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AplikacjeWielkoskalowe_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\AplikacjeWielkoskalowe_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET COMPATIBILITY_LEVEL = 130
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET ARITHABORT OFF 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET  READ_WRITE 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET  MULTI_USER 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AplikacjeWielkoskalowe] SET DELAYED_DURABILITY = DISABLED 
GO
USE [AplikacjeWielkoskalowe]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [AplikacjeWielkoskalowe]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [AplikacjeWielkoskalowe] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
